In [1]:
import pandas as pd

In [2]:
stop_data = pd.read_csv("stop_locations.txt", delimiter="|", header = None)
stop_data.columns = ["StopID", "StopNameShort", "StopNameLong", "StopType","SuburbName","PostCode","RegionName",
                     "LocalGovernmentArea","StatDivision","GPSLat","GPSLong"]

In [3]:
stop_data.head()

,StopID,StopNameShort,StopNameLong,StopType,SuburbName,PostCode,RegionName,LocalGovernmentArea,StatDivision,GPSLat,GPSLong
0,867,Weemala Court,Weemala Ct/Plenty River Dr (Greensborough),Kerbside,Greensborough,3088.0,Melbourne,Banyule,Greater Metro,-37.689596,145.105088
1,868,Crana Grove,Crana Gr/Plenty River Dr (Greensborough),Kerbside,Greensborough,3088.0,Melbourne,Banyule,Greater Metro,-37.686742,145.105588
2,869,Punkerri Circuit,Punkerri Cct/Plenty River Dr (Greensborough),Kerbside,Greensborough,3088.0,Melbourne,Banyule,Greater Metro,-37.683643,145.108743
3,870,Plenty River Drive,231 Plenty River Dr (Greensborough),Kerbside,Greensborough,3088.0,Melbourne,Banyule,Greater Metro,-37.682591,145.111331
4,875,Oldstead Rd,Oldstead Rd/Diamond Creek Rd (Greensborough),Kerbside,Greensborough,3088.0,Melbourne,Banyule,Greater Metro,-37.685336,145.117319

In [4]:
stop_data.describe()

             StopID      PostCode        GPSLat       GPSLong
count  27614.000000  27288.000000  27614.000000  27614.000000
mean   21756.656805   3290.487284    -37.701804    144.913593
std    15848.709416    292.232287      0.616607      0.801867
min        4.000000   2000.000000    -38.777124    138.579720
25%     8495.250000   3080.500000    -37.953394    144.794262
50%    17464.500000   3171.000000    -37.819235    145.026457
75%    37118.750000   3429.000000    -37.708218    145.182875
max    52126.000000   5290.000000    -33.873060    151.206390

In [5]:
stop_data.shape

(27614, 11)

In [6]:
any(pd.isnull(stop_data))

True

# Data cleaning needs to be done

In [7]:
stop_data[stop_data.isnull().any(axis=1)]

,StopID,StopNameShort,StopNameLong,StopType,SuburbName,PostCode,RegionName,LocalGovernmentArea,StatDivision,GPSLat,GPSLong
432,47196,Millar Rd,Millar Rd/Melrose Dr (Tullamarine),NaN,Tullamarine,3043.0,Melbourne,Hume,Greater Metro,-37.694808,144.875908
1313,30289,Chelmsford Av,Chelmsford Ave/Autumn St (Newtown (3220)),Kerbside,Newtown (3220),NaN,Geelong,Greater Geelong,Barwon & Western District,-38.139512,144.320158
1685,35474,Elsworth St,Elsworth St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.581623,143.867920
1686,35475,Burdeu St,Burdeu St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.579142,143.868010
1687,35476,Bradshaw St,Bradshaw St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.575223,143.868697
1688,35478,York St,York St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.569545,143.870199
1689,35479,Callow St,Callow St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.567803,143.868742
1690,35480,Cameron St,Cameron St/Barkly St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.570399,143.862002
1691,35481,Bradshaw St,Bradshaw St/Barkly St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.571550,143.860622
1692,35482,Pearces Park,Pearces Park/Barkly St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.573791,143.857967
1695,35485,Pearces Park,Pearces Park/Barkly St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.573753,143.857817
1696,35486,Bradshaw St,Bradshaw St/Barkly St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.571754,143.860190
1745,48501,St Mary's College,St Mary's College/McIntyre St (Seymour),NaN,Seymour,3660.0,Mitchell,Mitchell,Goulburn & Ovens-Murray,-37.021690,145.141295
1948,37451,Riverwood Village,Riverwood Village/Padman Dr (West Albury (NSW)),Kerbside,West Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.079422,146.890171
1949,37452,Solomon Street,Solomon St/Padman Dr (West Albury (NSW)),Kerbside,West Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.080122,146.895161
1950,37453,Albury West Public School,Albury West Public School/Mott St (West Albury...,Kerbside,West Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.077124,146.896449
1951,37454,Miller Street,Miller St/Mott St (West Albury (NSW)),Kerbside,West Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.075275,146.896813
1955,37458,Hovell Street,Hovell St/Macauly St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.088033,146.920977
1956,37459,Charles O'Neill House Units,Charles O'Neill House Units/Macauly St (South ...,Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.088035,146.920829
1957,37460,Bridge Street,Bridge St/Macauly St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.090819,146.920455
1958,37461,Macauly Street,Macauly St/Atkins St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.093711,146.919354
1959,37462,Olive Street,Olive St/Atkins St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.093320,146.916163
1960,37463,Panmure Street,Panmure St/Olive St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.095503,146.915565
1961,37464,Plummer Street,Plummer St/Abercorn St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.096914,146.913994
1962,37465,Panmure Street,Panmure St/Kiewa St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.094566,146.912980
1963,37466,Telstra,Telstra/Kiewa St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.089561,146.913918
1964,37467,Ebden Street,Ebden St/Olive St (South Albury (NSW)),Kerbside,South Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.088257,146.916761
1966,37471,Schubach Street,Schubach St/Centenary St (East Albury (NSW)),Kerbside,East Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.084641,146.927890
1967,37472,Wiedener Crescent,Wiedener Cres/Schubach St (East Albury (NSW)),Kerbside,East Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.087090,146.928110
1968,37473,Neve Street,Neve St/Weidner Cres (East Albury (NSW)),Kerbside,East Albury (NSW),NaN,New South Wales,Interstate,Interstate,-36.087576,146.930130
...,...,...,...,...,...,...,...,...,...,...,...
26164,35395,Peake St,Peake St/Grant St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.569940,143.863529
26165,35396,Grant St,Grant St/Magpie St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.571375,143.864807
26166,35397,Bradshaw St,Bradshaw St/Magpie St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.574120,143.864402
26167,35398,Sovereign Hill,Sovereign Hill/Bradshaw St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.574628,143.866184
26173,35416,Sovereign Hill,Sovereign Hill/Bradshaw St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.574735,143.866424
26174,35418,Bradshaw St,Bradshaw St/Magpie St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.574118,143.864266
26175,35419,Grant St,Grant St/Magpie St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.571267,143.864752
26176,35420,Peake St,Peake St/Grant St (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.570068,143.863395
26178,35422,Callow St,Callow St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.567941,143.868967
26179,35423,York St,York St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.569534,143.870367
26180,35426,Lal Lal St,Lal Lal St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.575538,143.868845
26181,35427,Burdeu St,Burdeu St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.579128,143.868219
26182,35428,Elsworth St,Elsworth St/Main Rd (Golden Point (3350)),Kerbside,Golden Point (3350),NaN,Ballarat,Ballarat,Central Highlands & Wimmera,-37.581619,143.868108
27045,23289,Allenby Road,Allenby Rd/Calder Park Dr (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.704305,144.756510
27046,23290,Community Hub,Community Hub/Calder Park Dr (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.701463,144.756027
27047,23291,Meade Way,Meade Way/Calder Park Dr (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.698278,144.755537
27048,23296,Sugar Gum Dr,Sugar Gum Dr/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.700960,144.742747
27049,23298,Allenby Rd,Allenby Rd/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.702904,144.742384
27068,23359,Allenby Rd,Allenby Rd/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.703024,144.742048
27069,23362,Sugar Gum Dr,Sugar Gum Dr/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.700870,144.742464
27070,23364,Parkwood Green PS,Parkwood Green PS/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.698027,144.743012
27071,23365,Parkwood Green PS,Parkwood Green PS/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.698059,144.743345
27072,23366,Tintern Loop,Tintern Lp/Gourlay Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.693383,144.743908
27507,46095,Caroline Springs College,Caroline Springs College/The Crossing (Carolin...,NaN,Caroline Springs,3023.0,Melbourne,Melton,Greater Metro,-37.735133,144.739026
27510,46756,Aspire Bvd,Aspire Bvd/Beattys Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.693325,144.727269
27511,46757,Sanctuary Rd,Sanctuary Rd/Beattys Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.692272,144.729843
27512,46758,Hillside Recreation Reserve,Hillside Recreation Reserve/Royal Cres (Hillsi...,Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.685571,144.739709
27513,46759,Sunningdale Dr,Sunningdale Dr/Sanctuary Rd (Hillside (3037)),Kerbside,Hillside (3037),NaN,Melbourne,Melton,Greater Metro,-37.691149,144.730386
27586,15351,Sunbury,Sunbury Railway Station (Sunbury),NaN,Sunbury,3429.0,Hume,Hume,Greater Metro,-37.579092,144.727320
27587,15353,Diggers Rest,Diggers Rest Railway Station (Diggers Rest),NaN,Diggers Rest,3427.0,Hume,Hume,Greater Metro,-37.627013,144.719918

In [8]:
stop_data['RegionName'].value_counts()

Melbourne               18246
Geelong                   823
Mornington Peninsula      742
Bendigo                   576
Ballarat                  558
Latrobe                   431
Bellarine Peninsula       412
Greater Shepparton        385
Mildura                   353
Yarra Ranges              345
Whittlesea                326
Hume                      311
Melton                    259
Warrnambool               243
New South Wales           191
Baw Baw                   169
Cardinia                  166
East Gippsland            157
Mitchell                  150
Greater Bendigo           147
Horsham                   142
Wangaratta                140
Bass Coast                135
Macedon Ranges            124
Surf Coast                122
Wellington                111
Campaspe                  109
Wodonga                   107
Central Goldfields        107
Otway                     106
                        ...
Mount Alexander            97
Moira                      92
Ararat                     87
Glenelg                    85
Southern Grampians         85
Wyndham                    82
Northern Grampians         77
Swan Hill                  74
Hepburn                    72
Murrindindi                58
Greater Ballarat           57
Benalla                    53
Phillip Island             53
Loddon                     36
South Gippsland            35
Yarriambiack               32
South Australia            30
Corangamite                27
Pyrenees                   24
Golden Plains              23
Indigo                     21
Alpine                     19
Mansfield                  18
Buloke                     16
Gannawarra                 12
West Wimmera               10
Hindmarsh                  10
Strathbogie                10
Towong                      8
ACT                         2
Name: RegionName, Length: 61, dtype: int64

### Getting stop data for only Melbourne Region

In [9]:
melb_stop_data = stop_data[stop_data["RegionName"]=="Melbourne"]

In [10]:
melb_stop_data.shape

(18246, 11)

In [11]:
columns = ["StopNameShort", "StopNameLong", "PostCode","LocalGovernmentArea","StatDivision"]
melb_stop_data = melb_stop_data.drop(columns, 1)

In [12]:
melb_stop_data.head(2)

   StopID  StopType     SuburbName RegionName     GPSLat     GPSLong
0     867  Kerbside  Greensborough  Melbourne -37.689596  145.105088
1     868  Kerbside  Greensborough  Melbourne -37.686742  145.105588

In [13]:
melb_stop_data["SuburbName"].value_counts()

Reservoir             326
Melbourne City        242
Preston               220
Werribee              211
Frankston             208
Berwick               203
Hoppers Crossing      186
Glen Waverley         182
Pakenham              170
Epping                164
Croydon               152
Ferntree Gully        151
Rowville              151
Coburg                142
Doncaster East        138
St Albans             138
Dandenong             137
Bundoora              137
Cheltenham            135
Mill Park             135
Bentleigh East        132
Wantirna South        128
Camberwell            124
Point Cook            123
Ringwood              121
Narre Warren          121
Footscray             120
Kew                   119
Craigieburn           119
Doncaster             118
                     ...
Moorabbin Airport       8
Eaglemont               8
Strathmore Heights      8
Belgrave Heights        8
Lower Plenty            8
Junction Village        8
Glen Huntly             7
Melbourne Airport       7
Essendon West           6
Eumemmerring            6
Seabrook                6
Hurstbridge             6
Ripponlea               6
Essendon North          6
Tottenham               5
Narre Warren East       5
Kooyong                 5
Ravenhall               5
Waterways               5
Wattle Glen             4
Attwood                 4
Keilor North            4
Warrandyte South        3
Calder Park             3
Cremorne                3
Keilor Lodge            2
Kurunjang               2
Seaholme                2
Sandhurst               2
Travancore              1
Name: SuburbName, Length: 333, dtype: int64

In [15]:
melb_stop_data["StopType"].value_counts()

Kerbside               14879
Bus Bay                 2300
Platform                 646
Safety Zone              329
non passenger point       52
kerbside                  11
Layover                    1
Depot                      1
Name: StopType, dtype: int64

In [ ]:
melb_stop_data = melb_stop_data.loc[melb_stop_data['StopType']==kerbside,:]

In [15]:
# removing lexiacl error from StopType, converting "kerbside" to "Kerbside"
melb_stop_data['StopType'][melb_stop_data['StopType']=="kerbside"] = "Kerbside"

C:\Users\shabb\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
melb_stop_data["StopType"].value_counts()

Kerbside               14890
Bus Bay                 2300
Platform                 646
Safety Zone              329
non passenger point       52
Layover                    1
Depot                      1
Name: StopType, dtype: int64

In [17]:
melb_stop_data[melb_stop_data["StopType"]=="non passenger point"]

       StopID             StopType       SuburbName     GPSLat     GPSLong
1277    13321  non passenger point  North Melbourne -37.789722  144.942508
1278    13404  non passenger point   Melbourne City -37.817224  144.953457
1279    13514  non passenger point   Melbourne City -37.819098  144.954412
1280    13576  non passenger point   Melbourne City -37.821098  144.955312
2356    12597  non passenger point        Southbank -37.823182  144.969919
2376    12750  non passenger point   Melbourne City -37.816179  144.972125
2377    12751  non passenger point   Melbourne City -37.815625  144.973868
2378    12764  non passenger point   Melbourne City -37.811735  144.964631
2384    12942  non passenger point      Mont Albert -37.814757  145.097747
3367    45627  non passenger point              Kew -37.812999  145.022870
3368    47919  non passenger point        Glen Iris -37.873460  145.031402
3369    47920  non passenger point          Malvern -37.862194  145.028454
3370    48079  non passenger point     Moonee Ponds -37.766663  144.925051
3372    48366  non passenger point          Preston -37.731260  145.014420
3707    48441  non passenger point  Caulfield North -37.872738  145.024908
8478    47922  non passenger point         Richmond -37.811761  145.013246
9250    14202  non passenger point   West Melbourne -37.801141  144.900869
9251    14203  non passenger point        Southbank -37.825316  144.956836
9320    45833  non passenger point    Fitzroy North -37.781891  144.977941
11312   20977  non passenger point   Melbourne City -37.813496  144.974005
12985   12749  non passenger point  South Melbourne -37.827450  144.953984
12986   13240  non passenger point         St Kilda -37.872522  144.989746
13327   52121  non passenger point           Coburg -37.756725  144.974874
13329   52123  non passenger point  North Melbourne -37.794024  144.947155
13330   52124  non passenger point        Northcote -37.752315  145.001678
13331   52126  non passenger point      South Yarra -37.838300  144.986534
19110   12659  non passenger point     Balwyn North -37.793004  145.072287
19111   12763  non passenger point              Kew -37.806582  145.031579
20171   46805  non passenger point       Camberwell -37.832844  145.068839
20184   47490  non passenger point              Kew -37.812999  145.022870
20190   48076  non passenger point        Glen Iris -37.853300  145.052708
20194   50209  non passenger point        Glen Iris -37.873460  145.031402
20778   50441  non passenger point      Elsternwick -37.883649  144.997211
21374   45607  non passenger point   Melbourne City -37.817857  144.964988
21375   45616  non passenger point   Melbourne City -37.815625  144.973868
21376   45646  non passenger point   Melbourne City -37.812217  144.962351
21627   45599  non passenger point      Elsternwick -37.883649  144.997211
21878   47917  non passenger point   Melbourne City -37.819098  144.954412
22840   45774  non passenger point   Melbourne City -37.811735  144.964631
22841   45805  non passenger point      Mont Albert -37.814757  145.097747
22846   45849  non passenger point  North Melbourne -37.805012  144.950843
22847   45865  non passenger point        Southbank -37.825316  144.956836
22870   47491  non passenger point   Melbourne City -37.812217  144.962351
22871   47492  non passenger point  North Melbourne -37.805012  144.950843
23027   47918  non passenger point          Windsor -37.857751  144.992479
23028   47921  non passenger point          Malvern -37.865076  145.050069
23041   48077  non passenger point           Toorak -37.843681  145.031205
23444   45632  non passenger point              Kew -37.806582  145.031579
23515   46515  non passenger point         St Kilda -37.851592  144.981105
23740   13059  non passenger point    Fitzroy North -37.781891  144.977941
23741   13114  non passenger point    Fitzroy North -37.780848  144.977880
24416   46517  non passenger point  Caulfield North -37.865477  145.025815

In [18]:
melb_stop_data[melb_stop_data["SuburbName"]=="Melbourne City"]

       StopID             StopType      SuburbName     GPSLat     GPSLong
361     19494             Platform  Melbourne City -37.808383  144.963328
362     19495             Platform  Melbourne City -37.810450  144.964267
363     19497             Platform  Melbourne City -37.813397  144.965608
364     19498             Platform  Melbourne City -37.816375  144.967019
365     19499             Platform  Melbourne City -37.818520  144.967992
369     19504          Safety Zone  Melbourne City -37.828827  144.971377
370     19505             Platform  Melbourne City -37.832618  144.972145
375     19511             Kerbside  Melbourne City -37.813516  144.951497
379     19519             Kerbside  Melbourne City -37.819160  144.961940
380     19520             Kerbside  Melbourne City -37.821507  144.954221
381     19522             Kerbside  Melbourne City -37.819080  144.961620
382     19526             Kerbside  Melbourne City -37.814978  144.968967
383     19527             Kerbside  Melbourne City -37.810002  144.966695
384     19528          Safety Zone  Melbourne City -37.835937  144.975381
386     19531             Kerbside  Melbourne City -37.808639  144.966305
387     19539          Safety Zone  Melbourne City -37.838855  144.976568
388     19540             Kerbside  Melbourne City -37.809014  144.969059
389     19541             Kerbside  Melbourne City -37.809722  144.971325
390     19542             Kerbside  Melbourne City -37.810440  144.968858
391     19545             Kerbside  Melbourne City -37.811564  144.965029
392     19546             Kerbside  Melbourne City -37.813897  144.957024
393     19547             Kerbside  Melbourne City -37.814810  144.952095
394     19548             Kerbside  Melbourne City -37.815010  144.952700
395     19549             Kerbside  Melbourne City -37.814401  144.954504
396     19550             Kerbside  Melbourne City -37.813454  144.957872
397     19551             Kerbside  Melbourne City -37.812634  144.960674
398     19554             Kerbside  Melbourne City -37.811310  144.965278
399     19555             Kerbside  Melbourne City -37.811330  144.965206
1278    13404  non passenger point  Melbourne City -37.817224  144.953457
1279    13514  non passenger point  Melbourne City -37.819098  144.954412
...       ...                  ...             ...        ...         ...
19487   18210          Safety Zone  Melbourne City -37.815440  144.958160
19488   18211          Safety Zone  Melbourne City -37.817460  144.959090
19489   18212          Safety Zone  Melbourne City -37.818440  144.959540
19490   18213             Kerbside  Melbourne City -37.818290  144.960370
19491   18214             Kerbside  Melbourne City -37.819517  144.961243
19508   18465          Safety Zone  Melbourne City -37.819430  144.961110
19509   18466          Safety Zone  Melbourne City -37.818540  144.960700
19510   18467             Kerbside  Melbourne City -37.818640  144.959770
19511   18469          Safety Zone  Melbourne City -37.817820  144.959170
20339    6553             Kerbside  Melbourne City -37.838287  144.976532
20340    6555             Kerbside  Melbourne City -37.843866  144.978651
20345    6614             Kerbside  Melbourne City -37.838410  144.976032
20346    6615             Kerbside  Melbourne City -37.844346  144.978483
21372   45470             Kerbside  Melbourne City -37.819272  144.953748
21373   45471             Kerbside  Melbourne City -37.819183  144.953408
21374   45607  non passenger point  Melbourne City -37.817857  144.964988
21375   45616  non passenger point  Melbourne City -37.815625  144.973868
21376   45646  non passenger point  Melbourne City -37.812217  144.962351
21727     925              Bus Bay  Melbourne City -37.824796  144.988593
21874   47744             Kerbside  Melbourne City -37.818541  144.963255
21878   47917  non passenger point  Melbourne City -37.819098  144.954412
21884   49999             Kerbside  Melbourne City -37.835910  144.975460
21888   51142             Kerbside  Melbourne City -37.829850  144.974220
21889   51143             Kerbside  Melbourne City -37.811790  144.959130
21890   51144             Kerbside  Melbourne City -37.812190  144.956770
21891   51145             Kerbside  Melbourne City -37.829700  144.974320
22840   45774  non passenger point  Melbourne City -37.811735  144.964631
22849   46437             Platform  Melbourne City -37.832580  144.971890
22869   47244             Kerbside  Melbourne City -37.810232  144.958402
22870   47491  non passenger point  Melbourne City -37.812217  144.962351

[242 rows x 5 columns]

## Checking data in Only  Berwick region, (selecting suburbname)

In [19]:
melb_stop_data[melb_stop_data["SuburbName"]=="Berwick"]["StopType"].value_counts()

Kerbside    156
Bus Bay      35
Platform      2
Name: StopType, dtype: int64

In [20]:
berwic_stop_data = melb_stop_data[melb_stop_data["SuburbName"]=="Berwick"]

In [21]:
berwic_stop_data[berwic_stop_data['StopID']==14782]

      StopID  StopType SuburbName     GPSLat     GPSLong
4865   14782  Kerbside    Berwick -38.032776  145.329833

In [22]:
melbcity_stop_data = melb_stop_data[melb_stop_data["SuburbName"]=="Melbourne City"]

In [23]:
melbcity_stop_data.shape

(242, 5)

In [24]:
berwic_stop_data.shape

(203, 5)

## Getting myki data

In [25]:
import os             
all_files = os.listdir("Samp_0/ScanOnTransaction/2015")

In [26]:
all_files

['Week27',
 'Week28',
 'Week29',
 'Week30',
 'Week31',
 'Week32',
 'Week33',
 'Week34',
 'Week35',
 'Week36',
 'Week37',
 'Week38',
 'Week39',
 'Week40',
 'Week41',
 'Week42',
 'Week43',
 'Week44',
 'Week45',
 'Week46',
 'Week47',
 'Week48',
 'Week49',
 'Week50',
 'Week51',
 'Week52',
 'Week53']

In [97]:
for i in all_files:
    j = os.listdir("Samp_0/ScanOffTransaction/2015/"+"Week27")
    for txt_file in j:
        fileName = "Samp_0/ScanOffTransaction/2015/"+"Week27"+ "/" + txt_file
        df = pd.read_csv(fileName, delimiter="|", header = None)
        break
    break

In [98]:
df.columns = ['Mode','BusinessDate','DateTime','CardID','CardType','VehicleID','ParentRoute','RouteID','StopID']
df.head()

,Mode,BusinessDate,DateTime,CardID,CardType,VehicleID,ParentRoute,RouteID,StopID
0,2,2015-07-01,2015-07-01 07:37:24,3791740,1,0,NaN,1,64404
1,2,2015-07-04,2015-07-04 15:12:12,13570550,1,0,NaN,1,64404
2,2,2015-07-04,2015-07-04 07:24:52,11206030,1,0,NaN,1,64404
3,2,2015-07-04,2015-07-04 07:21:37,10671870,1,0,NaN,1,64404
4,2,2015-07-03,2015-07-03 11:30:21,13513670,1,0,NaN,1,64404

In [99]:
df.shape

(272271, 9)

In [100]:
myki_stop_df = pd.merge(df, berwic_stop_data, how='inner', on=["StopID"])

In [101]:
myki_stop_df.shape

(858, 13)

In [102]:
myki_stop_df.head()

,Mode,BusinessDate,DateTime,CardID,CardType,VehicleID,ParentRoute,RouteID,StopID,StopType,SuburbName,GPSLat,GPSLong
0,2,2015-07-01,2015-07-01 17:30:37,11354730,1,0,NaN,14,19883,Platform,Berwick,-38.04041,145.345721
1,2,2015-07-03,2015-07-04 00:20:46,3175650,1,0,NaN,14,19883,Platform,Berwick,-38.04041,145.345721
2,2,2015-07-03,2015-07-03 18:19:52,13216270,65,0,NaN,14,19883,Platform,Berwick,-38.04041,145.345721
3,2,2015-07-02,2015-07-02 07:37:27,2184230,0,0,NaN,14,19883,Platform,Berwick,-38.04041,145.345721
4,2,2015-07-02,2015-07-02 19:43:49,12649920,1,0,NaN,14,19883,Platform,Berwick,-38.04041,145.345721

In [103]:
myki_stop_df["Mode"].value_counts()

2    578
1    280
Name: Mode, dtype: int64

In [104]:
#removing train stop and tram stop, selecting mode for bus
myki_stop_df = myki_stop_df[myki_stop_df["Mode"]==1]

In [105]:
myki_stop_df["StopType"].value_counts()

Bus Bay     147
Kerbside    132
Name: StopType, dtype: int64

In [106]:
myki_stop_df.groupby(["StopType", "StopID"]).size()

StopType  StopID
Bus Bay   3464       1
          3465       1
          3468       2
          3469       2
          3692       3
          3693       2
          3696       4
          3701       1
          3702       1
          4216       1
          4217       4
          14593      1
          14602      1
          21023     10
          21024     40
          21025     10
          22591      2
          22800      2
          23338      2
          40315     57
Kerbside  3467       5
          3694       2
          3697       9
          13503      4
          13504      2
          13507      1
          14588      1
          14594      2
          14595      1
          14597      2
                    ..
          14828      1
          14829      3
          14830      4
          14831      7
          14832      1
          14842      6
          14843      1
          14845      8
          18281      2
          18282      4
          22790      4
          22799      5
          22801      3
          23339      1
          41118      2
          41499      2
          45664      1
          45666      1
          45671      1
          45675      1
          45681      2
          45712      2
          45713      1
          45727      1
          45728      1
          45729      1
          45730      1
          45749      1
          45753      1
          45829      4
Length: 73, dtype: int64

In [107]:
test_df = myki_stop_df.groupby(["StopID"]).size()

In [108]:
test_df =  pd.DataFrame(test_df)

In [109]:
test_df.reset_index( inplace=True)

In [110]:
test_df.columns = ['StopId', "weekName"]

In [111]:
test_df.head()

   StopId  weekName
0    3464         1
1    3465         1
2    3467         5
3    3468         2
4    3469         2

In [113]:
test_df.to_csv("testFile.csv", sep=',')

In [114]:
# Week 28- touch OFF  
# for top 10 records
myki_stop_df.groupby(["StopType", "StopID"]).size().nlargest(10)
#myki_stop_df.groupby(["StopType", "StopID"]).size().head(10)

StopType  StopID
Bus Bay   40315     57
          21024     40
          21023     10
          21025     10
Kerbside  3697       9
          14845      8
          14599      7
          14831      7
          14842      6
          3467       5
dtype: int64

In [115]:
# week 28 - touch ON
# for top 10 records
myki_stop_df.groupby(["StopType", "StopID"]).size().nlargest(10)
#myki_stop_df.groupby(["StopType", "StopID"]).size().head(10)

StopType  StopID
Bus Bay   40315     57
          21024     40
          21023     10
          21025     10
Kerbside  3697       9
          14845      8
          14599      7
          14831      7
          14842      6
          3467       5
dtype: int64

In [116]:
#week 27 - touch ON
# for top 10 records
myki_stop_df.groupby(["StopType", "StopID"]).size().nlargest(10)
#myki_stop_df.groupby(["StopType", "StopID"]).size().head(10)

StopType  StopID
Bus Bay   40315     57
          21024     40
          21023     10
          21025     10
Kerbside  3697       9
          14845      8
          14599      7
          14831      7
          14842      6
          3467       5
dtype: int64

Checking for melcity region

In [ ]:
melbcity_myki_stop_df = pd.merge(df, melbcity_stop_data, how='inner', on=["StopID"])

In [ ]:
melbcity_myki_stop_df.shape

In [ ]:
melbcity_myki_stop_df.head()

In [ ]:
melbcity_myki_stop_df["Mode"].value_counts()

In [ ]:
#removing train stop and tram stop, selecting mode for bus
melbcity_myki_stop_df = melbcity_myki_stop_df[melbcity_myki_stop_df["Mode"]==1]

In [ ]:
melbcity_myki_stop_df["StopType"].value_counts()

In [ ]:
melbcity_myki_stop_df.groupby(["StopType", "StopID"]).size()

In [ ]:
 
# for top 10 records
melbcity_myki_stop_df.groupby(["StopType", "StopID"]).size().nlargest(10)
#myki_stop_df.groupby(["StopType", "StopID"]).size().head(10)

###  Removing subrurb records which have stops less than 10 in one suburb

In [50]:
s = melb_stop_data["SuburbName"].value_counts()
melb_stop_data = melb_stop_data[melb_stop_data.isin(s.index[s > 20]).values]

In [51]:
#removing rows with any null value
melb_stop_data = melb_stop_data.dropna(how='any')

In [52]:
melb_stop_data[melb_stop_data.isnull().any(axis=1)]

Empty DataFrame
Columns: [StopID, StopType, SuburbName, GPSLat, GPSLong]
Index: []

In [53]:
melb_stop_data.shape

(17332, 5)

## Counting stops in suburb

In [54]:
suburb_stop_count = melb_stop_data["SuburbName"].value_counts()

In [55]:
suburb_stop_count = pd.DataFrame(suburb_stop_count)

In [56]:
suburb_stop_count

                  SuburbName
Reservoir                326
Melbourne City           242
Preston                  220
Werribee                 211
Frankston                208
Berwick                  193
Hoppers Crossing         186
Glen Waverley            182
Pakenham                 168
Epping                   163
Croydon                  152
Rowville                 151
Ferntree Gully           151
Coburg                   142
St Albans                138
Doncaster East           138
Bundoora                 137
Dandenong                137
Cheltenham               135
Mill Park                135
Bentleigh East           132
Wantirna South           128
Camberwell               124
Point Cook               123
Narre Warren             121
Footscray                120
Kew                      119
Craigieburn              119
Ringwood                 118
Doncaster                118
...                      ...
North Warrandyte          27
Mount Eliza               27
Cranbourne West           27
Heidelberg                27
Brooklyn                  26
Albanvale                 26
Officer                   26
Carrum                    26
Mont Albert               25
Black Rock                25
Beaconsfield              25
Laverton                  24
Dallas                    24
Oakleigh East             24
Derrimut                  24
Kings Park                24
Williams Landing          23
Watsonia North            22
Warranwood                22
Eltham North              22
Research                  22
Docklands                 22
Viewbank                  22
Mckinnon                  22
Park Orchards             21
Abbotsford                21
Albion                    21
Alphington                21
Windsor                   21
Kingsbury                 21

[254 rows x 1 columns]

In [57]:
#resetting index
suburb_stop_count['SubName'] = suburb_stop_count.index

In [58]:
suburb_stop_count.columns = ["StopCount", "SuburbName"]

In [59]:
suburb_stop_count = suburb_stop_count.reset_index(drop="true")

In [60]:
suburb_stop_count.head()

   StopCount      SuburbName
0        326       Reservoir
1        242  Melbourne City
2        220         Preston
3        211        Werribee
4        208       Frankston

In [61]:
suburb_stop_count.shape

(254, 2)